In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv(r"C:\Users\pavani\OneDrive\Documents\fakenewsdata.csv")

In [3]:
data

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  label  
0      House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1      Ever get the feeling your life circles the rou...      0  
2      Why the Truth Might Get You Fired October 29, ...      1  
3      Videos 15 Civilians Killed In Single US Airstr...      1  
4      Print \nAn Iranian woman has been sentenced to...      1  
...                                                  ...    ...  
20795  Rapper T. I. unloaded on black celebrities who...      0  
20796  When the Green Bay Packers lost to the Washing...      0  
20797  The Macy’s of today grew from the union of sev...      0  
20798  NATO, Russia To Hold Parallel Exercises In Bal...      1  
20799    David Swanson is an author, activist, journa...      1  

[20800 rows x 5 columns]

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20800 entries, 0 to 20799
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      20800 non-null  int64 
 1   title   20242 non-null  object
 2   author  18843 non-null  object
 3   text    20761 non-null  object
 4   label   20800 non-null  int64 
dtypes: int64(2), object(3)
memory usage: 812.6+ KB


In [5]:
data.describe()

id         label
count  20800.000000  20800.000000
mean   10399.500000      0.500625
std     6004.587135      0.500012
min        0.000000      0.000000
25%     5199.750000      0.000000
50%    10399.500000      1.000000
75%    15599.250000      1.000000
max    20799.000000      1.000000

In [6]:
data.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [7]:
df=data.dropna()

In [8]:
df.isnull().sum()

id        0
title     0
author    0
text      0
label     0
dtype: int64

In [9]:
df

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  label  
0      House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1      Ever get the feeling your life circles the rou...      0  
2      Why the Truth Might Get You Fired October 29, ...      1  
3      Videos 15 Civilians Killed In Single US Airstr...      1  
4      Print \nAn Iranian woman has been sentenced to...      1  
...                                                  ...    ...  
20795  Rapper T. I. unloaded on black celebrities who...      0  
20796  When the Green Bay Packers lost to the Washing...      0  
20797  The Macy’s of today grew from the union of sev...      0  
20798  NATO, Russia To Hold Parallel Exercises In Bal...      1  
20799    David Swanson is an author, activist, journa...      1  

[18285 rows x 5 columns]

In [10]:
X = df.drop(['label'],axis=1)

In [11]:
y = df['label']

In [12]:
import tensorflow as tf

In [13]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [14]:
tf.__version__

'2.10.0'

In [15]:
# adjust the vocabulary size 
vocab_size=5000

In [16]:
# the most important steps for any type of lstm neural network:
# 1.one hot representation- to give proper index postion to the words in sentence
# 2. embedding layer using keras to genrate embedding matrix
# 3. adjust the vocab_size =10000(limit),dimensions = n n is based on the sentence lenght
# dimensions are nothing but the number of elements in the vector

In [17]:
mess = X.copy()

In [18]:
mess.reset_index(inplace=True) # to replace and restore the nan value space

In [42]:
import nltk
import re
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

In [20]:
nltk.download('stopwords')

[nltk_data] Error loading stopwords: <urlopen error [Errno 11001]
[nltk_data]     getaddrinfo failed>


False

In [21]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(mess)):
    print(i)
    review = re.sub('[^a-zA-Z]', ' ', mess['title'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

In [22]:
corpus # in order to remove the stopwords

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [23]:
onehot_repr=[one_hot(words,vocab_size)for words in corpus] 
onehot_repr

[[376, 3015, 3472, 194, 2824, 1523, 1414, 779, 1342, 2325],
 [4107, 502, 2725, 3779, 774, 3945, 4543],
 [4227, 1824, 3854, 4373],
 [3941, 1983, 4978, 3526, 2292, 4671],
 [2413, 774, 4418, 450, 629, 2651, 774, 2235, 3946, 4802],
 [738,
  2327,
  1433,
  1410,
  30,
  2278,
  3614,
  84,
  507,
  1589,
  1233,
  344,
  4458,
  4800,
  4543],
 [2386, 4133, 4220, 2587, 2385, 1798, 4745, 2720, 4740, 3055, 1111],
 [4685, 2645, 3819, 3515, 855, 638, 2278, 2170, 4740, 3055, 1111],
 [1561, 1698, 3314, 1554, 2351, 2278, 4329, 3595, 2278, 827],
 [883, 405, 1157, 61, 4484, 323, 2419, 4133],
 [717, 444, 3504, 1018, 4041, 3582, 487, 2346, 439, 2543, 4616],
 [3526, 3729, 2824, 2278, 2278, 855],
 [2534, 4871, 3478, 2247, 1127, 495, 1795, 4213, 4347],
 [3279, 3247, 732, 3648, 4332, 1691, 1621, 4740, 3055, 1111],
 [2016, 1719, 889, 704, 569, 4740, 3055, 1111],
 [2071, 2703, 3669, 3299, 686, 3369, 432, 3106, 1598, 1080],
 [3185, 332, 502],
 [2801, 2657, 1594, 4045, 2278, 4406, 2684, 4543],
 [4229, 1445, 

In [24]:
sen_len = 20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sen_len)
print(embedded_docs)

[[   0    0    0 ...  779 1342 2325]
 [   0    0    0 ...  774 3945 4543]
 [   0    0    0 ... 1824 3854 4373]
 ...
 [   0    0    0 ... 4740 3055 1111]
 [   0    0    0 ...  904 3438 2848]
 [   0    0    0 ... 1783  231  307]]


In [39]:
from tensorflow.keras.layers import Dropout
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(vocab_size,embedding_vector_features,input_length=sen_len))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [40]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 20, 40)            200000    
                                                                 
 dropout (Dropout)           (None, 20, 40)            0         
                                                                 
 lstm_1 (LSTM)               (None, 100)               56400     
                                                                 
 dropout_1 (Dropout)         (None, 100)               0         
                                                                 
 dense_1 (Dense)             (None, 1)                 101       
                                                                 
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________


In [41]:
X_new = np.array(embedded_docs)
y_new = np.array(y)

In [43]:
X_new.shape

(18285, 20)

In [44]:
y_new.shape

(18285,)

In [45]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X_new,y_new,test_size=0.2)

In [46]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
229/229 [==============================] - 9s 26ms/step - loss: 0.3223 - accuracy: 0.8604 - val_loss: 0.1982 - val_accuracy: 0.9152
Epoch 2/10
229/229 [==============================] - 5s 22ms/step - loss: 0.1473 - accuracy: 0.9409 - val_loss: 0.1922 - val_accuracy: 0.9223
Epoch 3/10
229/229 [==============================] - 5s 21ms/step - loss: 0.1135 - accuracy: 0.9566 - val_loss: 0.2121 - val_accuracy: 0.9130
Epoch 4/10
229/229 [==============================] - 5s 20ms/step - loss: 0.0915 - accuracy: 0.9658 - val_loss: 0.2265 - val_accuracy: 0.9100
Epoch 5/10
229/229 [==============================] - 4s 15ms/step - loss: 0.0700 - accuracy: 0.9755 - val_loss: 0.2435 - val_accuracy: 0.9174
Epoch 6/10
229/229 [==============================] - 4s 17ms/step - loss: 0.0545 - accuracy: 0.9811 - val_loss: 0.2928 - val_accuracy: 0.9040
Epoch 7/10
229/229 [==============================] - 5s 21ms/step - loss: 0.0434 - accuracy: 0.9858 - val_loss: 0.3360 - val_accuracy: 0.9109

In [50]:
from sklearn.metrics import accuracy_score

In [51]:
z_lstm = model.predict(X_test)

115/115 [==============================] - 1s 7ms/step


In [54]:
print(accuracy_score(y_test,z_lstm.round())*100)

91.49576155318567


In [72]:
test = model.predict(X_test[[5]])

1/1 [==============================] - 0s 33ms/step


In [73]:
test

array([[5.1719388e-05]], dtype=float32)

In [74]:
pred=np.argmax(test)

In [75]:
if(pred==0):
    print('postive')
else:
    print('negative')

postive


In [71]:
X_test

array([[   0,    0,    0, ..., 1691, 3609,  605],
       [   0,    0,    0, ...,  945, 1085, 4214],
       [   0,    0,    0, ..., 3173, 2423, 3878],
       ...,
       [   0,    0,    0, ...,  100, 4072, 2733],
       [   0,    0,    0, ...,  100, 4072, 2733],
       [   0,    0,    0, ..., 2989, 1539, 3030]])

In [25]:
X

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
20795  Rapper T. I. unloaded on black celebrities who...  
20796  When the Green Bay Packers lost to the Washing...  
20797  The Macy’s of today grew from the union of sev...  
20798  NATO, Russia To Hold Parallel Exercises In Bal...  
20799    David Swanson is an author, activist, journa...  

[18285 rows x 4 columns]

In [26]:
y

0        1
1        0
2        1
3        1
4        1
        ..
20795    0
20796    0
20797    0
20798    1
20799    1
Name: label, Length: 18285, dtype: int64

In [27]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [28]:
v = TfidfVectorizer()

In [29]:
v.fit(corpus)

TfidfVectorizer()

In [30]:
transform_output = v.transform(corpus)

In [31]:
print(v.vocabulary_)

{'hous': 5763, 'dem': 3128, 'aid': 225, 'even': 4104, 'see': 10930, 'comey': 2405, 'letter': 7007, 'jason': 6335, 'chaffetz': 2017, 'tweet': 12751, 'flynn': 4562, 'hillari': 5604, 'clinton': 2277, 'big': 1218, 'woman': 13672, 'campu': 1810, 'breitbart': 1537, 'truth': 12690, 'might': 7765, 'get': 4947, 'fire': 4462, 'civilian': 2218, 'kill': 6639, 'singl': 11252, 'us': 13066, 'airstrik': 247, 'identifi': 5881, 'iranian': 6226, 'jail': 6307, 'fiction': 4414, 'unpublish': 12973, 'stori': 11811, 'stone': 11799, 'death': 3009, 'adulteri': 144, 'jacki': 6295, 'mason': 7502, 'hollywood': 5678, 'would': 13712, 'love': 7208, 'trump': 12665, 'bomb': 1409, 'north': 8436, 'korea': 6735, 'lack': 6799, 'tran': 12562, 'bathroom': 1029, 'exclus': 4143, 'video': 13215, 'beno': 1151, 'hamon': 5348, 'win': 13616, 'french': 4717, 'socialist': 11426, 'parti': 8968, 'presidenti': 9557, 'nomin': 8415, 'new': 8316, 'york': 13821, 'time': 12418, 'back': 871, 'channel': 2040, 'plan': 9304, 'ukrain': 12802, 'ru

In [32]:
print(transform_output.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [33]:
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier

In [34]:
clf = Pipeline([('vectorizer_tfidf',TfidfVectorizer()),
               ('rfcc',RandomForestClassifier())])

In [35]:
from sklearn.model_selection import train_test_split

In [36]:
X_train,X_test,y_train,y_test = train_test_split(df.text,df.label,test_size=0.2,random_state=12)

In [37]:
clf.fit(X_train,y_train)

Pipeline(steps=[('vectorizer_tfidf', TfidfVectorizer()),
                ('rfcc', RandomForestClassifier())])

In [38]:
y_pred = clf.predict(X_test)

In [46]:
from sklearn.metrics import classification_report
from sklearn.ensemble import RandomForestClassifier

In [40]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.88      0.97      0.92      2091
           1       0.96      0.82      0.89      1566

    accuracy                           0.91      3657
   macro avg       0.92      0.90      0.90      3657
weighted avg       0.91      0.91      0.91      3657



In [41]:
test = ['apple is announcing new iphone tommorow']

In [44]:
review = re.sub('[^a-zA-Z]', ' ', test[0])
review = review.lower()
review = review.split()
    
review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
text_preprocessed = [' '.join(review)]

In [45]:
text_preprocessed

['appl announc new iphon tommorow']

In [48]:
rfcc = RandomForestClassifier()

In [51]:
clf.predict(text_preprocessed)[0]

1