In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('House data.csv')

In [3]:
df

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0        1          60       RL         65.0     8450   Pave   NaN      Reg   
1        2          20       RL         80.0     9600   Pave   NaN      Reg   
2        3          60       RL         68.0    11250   Pave   NaN      IR1   
3        4          70       RL         60.0     9550   Pave   NaN      IR1   
4        5          60       RL         84.0    14260   Pave   NaN      IR1   
...    ...         ...      ...          ...      ...    ...   ...      ...   
1455  1456          60       RL         62.0     7917   Pave   NaN      Reg   
1456  1457          20       RL         85.0    13175   Pave   NaN      Reg   
1457  1458          70       RL         66.0     9042   Pave   NaN      Reg   
1458  1459          20       RL         68.0     9717   Pave   NaN      Reg   
1459  1460          20       RL         75.0     9937   Pave   NaN      Reg   

     LandContour Utilities  ... PoolArea PoolQC  Fence MiscFeature MiscVal  \
0            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
2            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
3            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
4            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
...          ...       ...  ...      ...    ...    ...         ...     ...   
1455         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1456         Lvl    AllPub  ...        0    NaN  MnPrv         NaN       0   
1457         Lvl    AllPub  ...        0    NaN  GdPrv        Shed    2500   
1458         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1459         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   

     MoSold YrSold  SaleType  SaleCondition  SalePrice  
0         2   2008        WD         Normal     208500  
1         5   2007        WD         Normal     181500  
2         9   2008        WD         Normal     223500  
3         2   2006        WD        Abnorml     140000  
4        12   2008        WD         Normal     250000  
...     ...    ...       ...            ...        ...  
1455      8   2007        WD         Normal     175000  
1456      2   2010        WD         Normal     210000  
1457      5   2010        WD         Normal     266500  
1458      4   2010        WD         Normal     142125  
1459      6   2008        WD         Normal     147500  

[1460 rows x 81 columns]

In [4]:
df.isnull().sum()

Id                 0
MSSubClass         0
MSZoning           0
LotFrontage      259
LotArea            0
                ... 
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
SalePrice          0
Length: 81, dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             1460 non-null   int64  
 1   MSSubClass     1460 non-null   int64  
 2   MSZoning       1460 non-null   object 
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64  
 5   Street         1460 non-null   object 
 6   Alley          91 non-null     object 
 7   LotShape       1460 non-null   object 
 8   LandContour    1460 non-null   object 
 9   Utilities      1460 non-null   object 
 10  LotConfig      1460 non-null   object 
 11  LandSlope      1460 non-null   object 
 12  Neighborhood   1460 non-null   object 
 13  Condition1     1460 non-null   object 
 14  Condition2     1460 non-null   object 
 15  BldgType       1460 non-null   object 
 16  HouseStyle     1460 non-null   object 
 17  OverallQual    1460 non-null   int64  
 18  OverallC

In [6]:
df.drop(['SaleType','SaleCondition','MiscFeature','Fence','PoolQC','PavedDrive','GarageCond','GarageQual','GarageFinish',
         'GarageType','FireplaceQu','Functional','KitchenQual','Heating','HeatingQC','CentralAir','Electrical','Street','Alley',
         'LotShape','LandContour','Utilities'],axis=1)

Id  MSSubClass MSZoning  LotFrontage  LotArea LotConfig LandSlope  \
0        1          60       RL         65.0     8450    Inside       Gtl   
1        2          20       RL         80.0     9600       FR2       Gtl   
2        3          60       RL         68.0    11250    Inside       Gtl   
3        4          70       RL         60.0     9550    Corner       Gtl   
4        5          60       RL         84.0    14260       FR2       Gtl   
...    ...         ...      ...          ...      ...       ...       ...   
1455  1456          60       RL         62.0     7917    Inside       Gtl   
1456  1457          20       RL         85.0    13175    Inside       Gtl   
1457  1458          70       RL         66.0     9042    Inside       Gtl   
1458  1459          20       RL         68.0     9717    Inside       Gtl   
1459  1460          20       RL         75.0     9937    Inside       Gtl   

     Neighborhood Condition1 Condition2  ... WoodDeckSF OpenPorchSF  \
0         CollgCr       Norm       Norm  ...          0          61   
1         Veenker      Feedr       Norm  ...        298           0   
2         CollgCr       Norm       Norm  ...          0          42   
3         Crawfor       Norm       Norm  ...          0          35   
4         NoRidge       Norm       Norm  ...        192          84   
...           ...        ...        ...  ...        ...         ...   
1455      Gilbert       Norm       Norm  ...          0          40   
1456       NWAmes       Norm       Norm  ...        349           0   
1457      Crawfor       Norm       Norm  ...          0          60   
1458        NAmes       Norm       Norm  ...        366           0   
1459      Edwards       Norm       Norm  ...        736          68   

      EnclosedPorch  3SsnPorch  ScreenPorch  PoolArea MiscVal MoSold YrSold  \
0                 0          0            0         0       0      2   2008   
1                 0          0            0         0       0      5   2007   
2                 0          0            0         0       0      9   2008   
3               272          0            0         0       0      2   2006   
4                 0          0            0         0       0     12   2008   
...             ...        ...          ...       ...     ...    ...    ...   
1455              0          0            0         0       0      8   2007   
1456              0          0            0         0       0      2   2010   
1457              0          0            0         0    2500      5   2010   
1458            112          0            0         0       0      4   2010   
1459              0          0            0         0       0      6   2008   

     SalePrice  
0       208500  
1       181500  
2       223500  
3       140000  
4       250000  
...        ...  
1455    175000  
1456    210000  
1457    266500  
1458    142125  
1459    147500  

[1460 rows x 59 columns]

In [7]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [8]:
x=df.select_dtypes(include='object').columns
print(x)

Index(['MSZoning', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities',
       'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2',
       'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st',
       'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation',
       'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2',
       'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual',
       'Functional', 'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual',
       'GarageCond', 'PavedDrive', 'PoolQC', 'Fence', 'MiscFeature',
       'SaleType', 'SaleCondition'],
      dtype='object')


In [9]:
for i in x:
    df[i]=le.fit_transform(df[i].astype(str))
print(df.info())    

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             1460 non-null   int64  
 1   MSSubClass     1460 non-null   int64  
 2   MSZoning       1460 non-null   int32  
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64  
 5   Street         1460 non-null   int32  
 6   Alley          1460 non-null   int32  
 7   LotShape       1460 non-null   int32  
 8   LandContour    1460 non-null   int32  
 9   Utilities      1460 non-null   int32  
 10  LotConfig      1460 non-null   int32  
 11  LandSlope      1460 non-null   int32  
 12  Neighborhood   1460 non-null   int32  
 13  Condition1     1460 non-null   int32  
 14  Condition2     1460 non-null   int32  
 15  BldgType       1460 non-null   int32  
 16  HouseStyle     1460 non-null   int32  
 17  OverallQual    1460 non-null   int64  
 18  OverallC

In [10]:
df

Id  MSSubClass  MSZoning  LotFrontage  LotArea  Street  Alley  \
0        1          60         3         65.0     8450       1      2   
1        2          20         3         80.0     9600       1      2   
2        3          60         3         68.0    11250       1      2   
3        4          70         3         60.0     9550       1      2   
4        5          60         3         84.0    14260       1      2   
...    ...         ...       ...          ...      ...     ...    ...   
1455  1456          60         3         62.0     7917       1      2   
1456  1457          20         3         85.0    13175       1      2   
1457  1458          70         3         66.0     9042       1      2   
1458  1459          20         3         68.0     9717       1      2   
1459  1460          20         3         75.0     9937       1      2   

      LotShape  LandContour  Utilities  ...  PoolArea  PoolQC  Fence  \
0            3            3          0  ...         0       3      4   
1            3            3          0  ...         0       3      4   
2            0            3          0  ...         0       3      4   
3            0            3          0  ...         0       3      4   
4            0            3          0  ...         0       3      4   
...        ...          ...        ...  ...       ...     ...    ...   
1455         3            3          0  ...         0       3      4   
1456         3            3          0  ...         0       3      2   
1457         3            3          0  ...         0       3      0   
1458         3            3          0  ...         0       3      4   
1459         3            3          0  ...         0       3      4   

      MiscFeature  MiscVal  MoSold  YrSold  SaleType  SaleCondition  SalePrice  
0               4        0       2    2008         8              4     208500  
1               4        0       5    2007         8              4     181500  
2               4        0       9    2008         8              4     223500  
3               4        0       2    2006         8              0     140000  
4               4        0      12    2008         8              4     250000  
...           ...      ...     ...     ...       ...            ...        ...  
1455            4        0       8    2007         8              4     175000  
1456            4        0       2    2010         8              4     210000  
1457            2     2500       5    2010         8              4     266500  
1458            4        0       4    2010         8              4     142125  
1459            4        0       6    2008         8              4     147500  

[1460 rows x 81 columns]

In [11]:
df['GarageYrBlt'].fillna(df['GarageYrBlt'].mean(),inplace=True)
df['LotFrontage'].fillna(df['LotFrontage'].mean(),inplace=True)
df['MasVnrArea'].fillna(df['MasVnrArea'].mean(),inplace=True)

In [12]:
df.isnull().sum()

Id               0
MSSubClass       0
MSZoning         0
LotFrontage      0
LotArea          0
                ..
MoSold           0
YrSold           0
SaleType         0
SaleCondition    0
SalePrice        0
Length: 81, dtype: int64

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             1460 non-null   int64  
 1   MSSubClass     1460 non-null   int64  
 2   MSZoning       1460 non-null   int32  
 3   LotFrontage    1460 non-null   float64
 4   LotArea        1460 non-null   int64  
 5   Street         1460 non-null   int32  
 6   Alley          1460 non-null   int32  
 7   LotShape       1460 non-null   int32  
 8   LandContour    1460 non-null   int32  
 9   Utilities      1460 non-null   int32  
 10  LotConfig      1460 non-null   int32  
 11  LandSlope      1460 non-null   int32  
 12  Neighborhood   1460 non-null   int32  
 13  Condition1     1460 non-null   int32  
 14  Condition2     1460 non-null   int32  
 15  BldgType       1460 non-null   int32  
 16  HouseStyle     1460 non-null   int32  
 17  OverallQual    1460 non-null   int64  
 18  OverallC

In [14]:
df.to_csv('newhousedata.csv')

In [15]:
df.shape

(1460, 81)

In [16]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor
from sklearn import metrics
from sklearn.metrics import accuracy_score,confusion_matrix

In [17]:
X=df.iloc[:,:80].values # df.drop([''],axis=1)

In [18]:
print(X)

[[1.000e+00 6.000e+01 3.000e+00 ... 2.008e+03 8.000e+00 4.000e+00]
 [2.000e+00 2.000e+01 3.000e+00 ... 2.007e+03 8.000e+00 4.000e+00]
 [3.000e+00 6.000e+01 3.000e+00 ... 2.008e+03 8.000e+00 4.000e+00]
 ...
 [1.458e+03 7.000e+01 3.000e+00 ... 2.010e+03 8.000e+00 4.000e+00]
 [1.459e+03 2.000e+01 3.000e+00 ... 2.010e+03 8.000e+00 4.000e+00]
 [1.460e+03 2.000e+01 3.000e+00 ... 2.008e+03 8.000e+00 4.000e+00]]


In [19]:
y=df.iloc[:,80].values

In [20]:
print(y)

[208500 181500 223500 ... 266500 142125 147500]


In [72]:
X_train,X_test,y_train,y_test=train_test_split(X_scaled,y_scaled,test_size=0.1,random_state=4)

In [22]:
lr=LinearRegression()
dtrr=DecisionTreeRegressor()
svmm=SVR()
rfrr=RandomForestRegressor()

In [23]:
lr.fit(X_train,y_train)

LinearRegression()

In [24]:
dtrr.fit(X_train,y_train)

DecisionTreeRegressor()

In [25]:
svmm.fit(X_train,y_train)

SVR()

In [26]:
rfrr.fit(X_train,y_train)

RandomForestRegressor()

In [27]:
z1=lr.predict(X_train)

In [28]:
z2=dtrr.predict(X_train)

In [29]:
z3=rfrr.predict(X_train)

In [30]:
r2_score=metrics.r2_score(y_train,z1)

In [31]:
r2_score

0.850187205544039

In [32]:
r2_score1=metrics.r2_score(y_train,z3)

In [33]:
r2_score1

0.9810585341364265

In [34]:
print('predicted_val:',dtrr.predict([[1,60,3,65,8450,1,2,3,3,0,4,0,5,2,2,0,5,7,5,2003,2020,1,1,12,13,1,196,2,4,2,2,3,3,2,706,5,0,150,856,1,0,1,4,856,854,0,1710,1,0,2,1,3,1,2,8,6,0,5,1,
                                     2003,1,2,548,4,4,2,0,61,0,0,0,0,3,4,4,0,2,2020,8,4]]))

predicted_val: [208500.]


In [43]:
import joblib

In [41]:
joblib.dump(dtrr,'newhousedatamodel.pkl')

['newhousedatamodel.pkl']

In [39]:
joblib.dump(le,'newhouseencoder.pkl')

['newhouseencoder.pkl']

In [35]:
X

array([[1.000e+00, 6.000e+01, 3.000e+00, ..., 2.008e+03, 8.000e+00,
        4.000e+00],
       [2.000e+00, 2.000e+01, 3.000e+00, ..., 2.007e+03, 8.000e+00,
        4.000e+00],
       [3.000e+00, 6.000e+01, 3.000e+00, ..., 2.008e+03, 8.000e+00,
        4.000e+00],
       ...,
       [1.458e+03, 7.000e+01, 3.000e+00, ..., 2.010e+03, 8.000e+00,
        4.000e+00],
       [1.459e+03, 2.000e+01, 3.000e+00, ..., 2.010e+03, 8.000e+00,
        4.000e+00],
       [1.460e+03, 2.000e+01, 3.000e+00, ..., 2.008e+03, 8.000e+00,
        4.000e+00]])

In [36]:
y

array([208500, 181500, 223500, ..., 266500, 142125, 147500], dtype=int64)

In [37]:
from sklearn.preprocessing import MinMaxScaler

In [38]:
mm=MinMaxScaler()

In [39]:
X_scaled=mm.fit_transform(X)

In [40]:
mm1=MinMaxScaler()

In [42]:
y_rescaped=y.reshape(-1,1)

In [43]:
y_scaled=mm1.fit_transform(y_rescaped)

In [44]:
y_scaled.shape

(1460, 1)

In [45]:
X_scaled.shape

(1460, 80)

In [47]:
import tensorflow.keras

In [48]:
from keras.models import Sequential
from keras.layers import Dense

In [49]:
ann=Sequential()

In [97]:
ann.add(Dense(64,input_dim=81,activation='relu')) # input layer
ann.add(Dense(64,activation='relu')) # hidden layer
ann.add(Dense(1,activation='linear'))

In [98]:
ann.compile(optimizer='adam',loss='mean_squared_error')

In [99]:
X_train.shape

(1314, 80)

In [100]:
y_train.shape

(1314, 1)

In [101]:
y_train.reshape(-1,1).shape

(1314, 1)

In [102]:
history=ann.fit(X_train,y_train,epochs=20,verbose=1)

Epoch 1/20


ValueError: in user code:

    File "C:\Users\pavani\anaconda3\lib\site-packages\keras\engine\training.py", line 1160, in train_function  *
        return step_function(self, iterator)
    File "C:\Users\pavani\anaconda3\lib\site-packages\keras\engine\training.py", line 1146, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\pavani\anaconda3\lib\site-packages\keras\engine\training.py", line 1135, in run_step  **
        outputs = model.train_step(data)
    File "C:\Users\pavani\anaconda3\lib\site-packages\keras\engine\training.py", line 993, in train_step
        y_pred = self(x, training=True)
    File "C:\Users\pavani\anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "C:\Users\pavani\anaconda3\lib\site-packages\keras\engine\input_spec.py", line 295, in assert_input_compatibility
        raise ValueError(

    ValueError: Input 0 of layer "sequential" is incompatible with the layer: expected shape=(None, 81), found shape=(None, 80)
